import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { Toaster } from "sonner";
import AuthSessionProvider from "@/components/Providers/SessionProvider";

export const metadata: Metadata = {
  title: "shop mart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthSessionProvider>
          <Toaster position="top-center" />
          <Navbar />
          <div className="container">{children}</div>
          <Footer />
        </AuthSessionProvider>
      </body>
    </html>
  );
}
